import re, os
WT = "/tmp/equipo-electricista-20261004-2100/"
os.chdir(WT)
def rd(f): return open(f, encoding='utf-8').read()
def styles(s): return re.findall(r'<style[^>]*>(.*?)</style>', s, re.S)
for f in ['index.html', 'contacto/index.html', 'blog/index.html']:
    s = rd(f); st = styles(s); inl = ''.join(st)
    print(f, '| <style>', len(st), '| .btn-primary{ inline:', len(re.findall(r'\.btn-primary\s*\{', inl)),
          '| usos:', len(re.findall(r'class="[^"]*btn-primary', s)), '| :root:', ':root' in inl,
          '| gradient-brand:', re.findall(r'--gradient-brand:([^;]+);', inl)[:1])
s = rd('index.html')
m = re.search(r'\.btn-primary\s*\{[^}]*\}', ''.join(styles(s)))
print('HOME .btn-primary:', m.group(0) if m else None)
c = rd('styles.7f293647.css')
m = re.search(r'\.btn-whatsapp\s*\{[^}]*\}', c); print('CSS .btn-whatsapp:', m.group(0) if m else None)
print('--whatsapp:', re.findall(r'--whatsapp:([^;]+);', c)[:2])
cc = rd('contacto/index.html')
print('contacto primer style termina en:', repr(styles(cc)[0][-90:]))
print('contacto link css:', re.findall(r'<link[^>]*styles\.7f293647[^>]*>', cc)[:2])
print('contacto btn usos:', re.findall(r'<a[^>]*class="[^"]*btn-primary[^"]*"[^>]*>', cc)[:3])
b = rd('blog/index.html')
print('blog btn usos:', re.findall(r'<a[^>]*class="[^"]*btn-primary[^"]*"[^>]*>', b)[:3])
print('blog link css:', re.findall(r'<link[^>]*styles\.7f293647[^>]*>', b)[:2])
print('blog style termina en:', repr(styles(b)[0][-90:]) if styles(b) else None)
a = rd('blog/apagones-culiacan-por-que-se-va-la-luz-que-hacer/index.html')
print('T2 title:', re.findall(r'<title>(.*?)</title>', a)); print('h1:', re.findall(r'<h1[^>]*>(.*?)</h1>', a, re.S)[:1])
print('og/tw title:', re.findall(r'(og:title|twitter:title)"[^>]*content="([^"]+)', a))
print('desc:', re.findall(r'name="description"[^>]*content="([^"]+)', a))
print('og/tw desc:', re.findall(r'(og:description|twitter:description)"[^>]*content="([^"]+)', a))
print('headline:', re.findall(r'"headline"\s*:\s*"([^"]+)', a)); print('dateModified:', re.findall(r'"dateModified"\s*:\s*"([^"]+)', a))
print('veces cadena vieja:', a.count('Apagón en Culiacán: por qué'))
print('names:', re.findall(r'"name"\s*:\s*"(Apag[^"]+)', a))
l = rd('blog/ahorro-energia-iluminacion-led/index.html')
print('T3:', len(re.findall(r'mejores\s+decisión ', l)), len(re.findall(r'mejores\s+decisiones', l)))
